// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/:id', function(req, res) {
    res.render('programa', {
      title: "Programa " + req.params.id
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=programa.map
